USE EMPRESARIAL;
CREATE TABLE PROJETO_ATIVIDADE (
CD_PROJ CHAR(6),
CD_ATIV INT(3),
DT_INI DATE,
DT_FIM DATE,
PRIMARY KEY (CD_PROJ, CD_ATIV),
FOREIGN KEY (CD_PROJ) REFERENCES PROJ(CD_PROJ),
FOREIGN KEY (CD_ATIV) REFERENCES ATIV(CD_ATIV)
);

CREATE TABLE PROJ(
CD_PROJ CHAR(6), 
NM_PROJ VARCHAR (30),
CD_DEPTO CHAR (6), 
QT_EQP INT, 
QT_INI DATE,
DT_FIM DATE,
PRIMARY KEY(CD_PROJ),
FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO(CD_DEPTO)
);

CREATE TABLE DEPTO(
CD_DEPTO CHAR (6),
NM_DEPTO VARCHAR(40),
CD_GERENTE INT (5),
CD_DEPTO_CTB CHAR (5),
PRIMARY KEY (CD_DEPTO)
);

CREATE TABLE FUNC(
CD_MAT INT (5),
NM_FUNC VARCHAR (12),
NM_SOBRENOME VARCHAR (12),
CD_DEPTO CHAR (3),
NR_RAMAL INT (4),
DT_ADM DATE,
NR_CARGO INT (3),
NR_RG INT (2),
IN_SEXO VARCHAR (1),
DT_NASC DATE,
VL_SAL INT (9.2),
NM_FOTO VARCHAR (100),
PRIMARY KEY(CD_MAT)
);

CREATE TABLE HST_PROMO(
CD_MAT INT(5),
CD_DEPTO CHAR(3),
DT_PROMOCAO DATE,
VL_SAL INT(9.2),
NR_CARGO INT(3),
TX_MOTIVO VARCHAR (200),
PRIMARY KEY(CD_MAT, CD_DEPTO)
);

CREATE TABLE ativ (
  CD_ATIV int(3) NOT NULL,
  NM_SIGLA varchar(12),
  TX_DESCRICAO varchar(30),
  PRIMARY KEY (CD_ATIV)
);




/*CRIA NOVO FUNCIONARIO*/
/*INSERT INTO DEPTO (CD_DEPTO, NM_DEPTO, CD_GERENTE, CD_DEPTO_CTB)  VALUES (2,'RH', 5, 12);*/
/*INSERT INTO FUNC (CD_MAT, NM_FUNC, NM_SOBRENOME, VL_SAL, CD_DEPTO, IN_SEXO, NR_CARGO) VALUES (2,'MARCELO', 'SALGADO', 1743, 2, 'M', 55);*/
/*INSERT INTO ATIV (CD_ATIV, NM_SIGLA, TX_DESCRICAO) VALUES (3, 'BD', 'UTILIZANDO BANCO DE DADOS');*/
/*INSERT INTO PROJ (CD_PROJ, NM_PROJ, CD_DEPTO, QT_EQP, DT_INI, DT_FIM) VALUES (2, 'SISTEMA WEB', 2, 30, '2013-04-02', '2024-01-01');*/
/*INSERT INTO PROJETO_ATIVIDADE (CD_PROJ, CD_ATIV, DT_INI, DT_FIM) VALUES (2, 3, '2013-04-02', '2024-01-01');*/

